branches:
  - master
  - release

build:
  image: php
  commands:
    - 'make syntax.checker'
    # Build release
    - 'apt-get update'
    - 'sudo apt-get install zip'
    - 'make zip s3.path=wild-style/'
    - 'make style.req style'
    - 'make zip'

deploy:
  rsync:
    user: $$DEPLOY_USER
    host: woo.aplazame.com
    target: $$RELEASE_PATH
    delete: true
    recursive: true

  s3:
    acl: public-read
    region: $$S3_REGION
    bucket: $$S3_BUCKET
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: .s3
    target: /modules/woocommerce
    recursive: true
    when:
      branch: release

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: 'drone'
    channel: 'developers'
    when:
      success: false
      failure: true
      change: true

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASS
    recipients:
      - dev@aplazame.com
    when:
      success: false
      failure: true
      change: true
