version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      - WORDPRESS_URL=http://woo.aplazame
      - WORDPRESS_DEBUG=true
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=password
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins/aplazame
    ports:
      - "80:80"

  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    ports:
      - "3306:3306"

  i18n:
    build:
      dockerfile: Dockerfile.i18n
      context: ./
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: make i18n

  style:
    build:
      dockerfile: Dockerfile.style
      context: ./
    volumes:
      - ./plugin:/project/plugin
