version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      - WORDPRESS_URL=http://woo.aplazame
      - WORDPRESS_DEBUG=true
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=password
    networks:
      - internal
      - public
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins/aplazame
    ports:
      - "80:80"

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    networks:
      - internal

  l10n:
    build:
      dockerfile: Dockerfile_l10n
      context: ./
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: make l10n

networks:
  internal:
  public:
