version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    working_directory: ~/aplazame
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist

      - run:
          name: Check Syntax
          command: make syntax.checker

      - run:
          name: CS
          command: make style

  deploy_to_s3:
    machine:
      enabled: true
    working_directory: ~/aplazame
    steps:
      - run:
          name: Create bundle
          command: make zip

      - run:
          name: Deploy to S3 when release
          command: aws s3 sync aplazame.latest.zip s3://aplazame/modules/woocommerce/ --delete

  deploy_to_wordpress:
    machine:
      enabled: true
    working_directory: ~/aplazame
    steps:
      - run:
          name: Install dependencies
          command: sudo apt install -y rsync

      - run:
          name: Clone wordpress repository
          command: svn co https://plugins.svn.wordpress.org/aplazame svn

      - run:
          name: Sync assets
          command: rsync -r -p assets/* svn/assets

      - run:
          name: Sync trunk
          command: rsync -r -p plugin/* svn/trunk

      - run:
          name: Tag release
          command: svn cp svn/trunk svn/tags/${CIRCLECI_TAG:1}

      - run:
          name: Commit
          command: svn ci --no-auth-cache --username $WP_USERNAME --password $WP_PASSWORD svn -m "tagging version ${CIRCLECI_TAG:1}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
          filters:
            tags:
              only: /.*/
      - deploy_to_s3:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_to_wordpress:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
